FROM golang:alpine3.19 AS builder

RUN apk update && apk add --no-cache git
RUN apk add --no-cache make

WORKDIR /app

COPY *.mod *.sum ./
RUN go mod download

COPY . .

RUN make api_build

FROM scratch

COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=builder /app/bin/api /go/bin/api

EXPOSE ${APPLICATION_PORT}

ENTRYPOINT ["/go/bin/api"]
